# Generated by Django 3.0 on 2021-04-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210415_1428'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ddd',
        ),
        migrations.AlterField(
            model_name='selecteddata',
            name='user',
            field=models.CharField(max_length=255),
        ),
    ]
